export const LOGIN = '/login'
export const SIGNUP = '/signin'
export const PROFILE = '/profile'
export const DASHBOARD = '/dashboard'
export const FORGETPASSWORD = '/forgetpassword'
export const APP = '/' 